// request
export const REQUEST_SET_ERROR = 'REQUEST_SET_ERROR';
export const REQUEST_SET_SUCCESS = 'REQUEST_SET_SUCCESS';
export const REQUEST_SET_MESSAGE = 'REQUEST_SET_MESSAGE';
export const REQUEST_RESET = 'REQUEST_RESET';

// auth
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_RESET = 'AUTH_RESET';

// theme
export const THEME_CHANGE_THEME = 'THEME_CHANGE_THEME';

// profile
export const PROFILE_SET_DATA = 'PROFILE_SET_DATA';
export const PROFILE_RESET = 'PROFILE_RESET';

// collections
export const COLLECTIONS_SET_COLLECTIONS = 'COLLECTIONS_SET_COLLECTIONS';
export const COLLECTIONS_ADD_COLLECTION = 'COLLECTIONS_ADD_COLLECTION';
export const COLLECTIONS_DELETE_COLLECTION = 'COLLECTIONS_DELETE_COLLECTION';
export const COLLECTIONS_EDIT_COLLECTION = 'COLLECTIONS_EDIT_COLLECTION';
export const COLLECTIONS_RESET = 'COLLECTIONS_RESET';

// collection
export const COLLECTION_RESET_COLLECTION = 'COLLECTION_RESET_COLLECTION';
export const COLLECTION_SET_COLLECTION = 'COLLECTION_SET_COLLECTION';
export const COLLECTION_FLIP_CARD = 'COLLECTION_FLIP_CARD';
