// app
export const APP_SET_LOADING = 'APP_SET_LOADING'
export const APP_SET_ERROR = 'APP_SET_ERROR'
export const APP_SET_SUCCESS = 'APP_SET_SUCCESS'
export const APP_SET_MESSAGE = 'APP_SET_MESSAGE'
export const APP_RESET = 'APP_RESET'

// auth
export const AUTH_SET_USER = 'AUTH_SET_USER'
export const AUTH_RESET = 'AUTH_RESET'

// profile
export const PROFILE_SET_DATA = 'PROFILE_SET_DATA'
export const PROFILE_RESET = 'PROFILE_RESET'

// collections
export const COLLECTIONS_FETCH_COLLECTIONS = 'COLLECTIONS_FETCH_COLLECTIONS'
export const COLLECTIONS_SET_CURRENT_COLLECTION = 'COLLECTIONS_SET_CURRENT_COLLECTION'
export const COLLECTIONS_ADD_COLLECTION = 'COLLECTIONS_ADD_COLLECTION'
export const COLLECTIONS_DELETE_COLLECTION = 'COLLECTIONS_DELETE_COLLECTION'
export const COLLECTIONS_RESET = 'COLLECTIONS_RESET'

// cards
export const CARDS_SET_CARDS = 'CARDS_SET_CARDS'
export const CARDS_FLIP_CARD = 'CARDS_FLIP_CARD'

// menu
export const MENU_OPEN_MENU = 'MENU_OPEN_MENU'
export const MENU_CLOSE_MENU = 'MENU_CLOSE_MENU'
